### ISSUE TITLE
无法获取实体类，对应的表名

### ISSUE THREAD

**Issue by zhmingGIT** [abel533/MyBatis-Spring-Boot#18]
Caused by: java.lang.RuntimeException: 无法获取实体类cn.dceast.model.User对应的表名!
	at tk.mybatis.mapper.mapperhelper.EntityHelper.getEntityTable(EntityHelper.java:65) ~[mapper-3.3.9.jar:na]
	at tk.mybatis.mapper.entity.Example.<init>(Example.java:93) ~[mapper-3.3.9.jar:na]
	at tk.mybatis.mapper.entity.Example.<init>(Example.java:78) ~[mapper-3.3.9.jar:na]
	at tk.mybatis.mapper.entity.Example.<init>(Example.java:68) ~[mapper-3.3.9.jar:na]
	at cn.dceast.config.security.SecurityConfig$1.loadUserByUsername(SecurityConfig.java:63) ~[classes/:na]
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:114) ~[spring-security-core-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	... 45 common frames omitted

//出错行
 Example example = new Example(User.class);

//实体
@Data
public class User extends BaseEntity implements UserDetails {

    private String username;
    private String password;
    private String role;

**Comment by abel533** [comment]
必须有该实体类对应的 Mapper 接口

**Comment by zhmingGIT** [comment]
有的啊

public interface UserMapper extends MyMapper<User> {



}

**Comment by zhmingGIT** [comment]
public interface UserMapper extends MyMapper<User> {

  

}

**Comment by zhmingGIT** [comment]
MyMapper<User>

**Comment by zhmingGIT** [comment]
<User>加了

**Comment by zhmingGIT** [comment]
有的啊

public interface UserMapper extends MyMapper<User> {

  

}
git上的回复 <User>这个显示不出来 。。。




 
发件人： Liuzh
发送时间： 2017-01-25 21:58
收件人： abel533/MyBatis-Spring-Boot
抄送： zhengm; Author
主题： Re: [abel533/MyBatis-Spring-Boot] 无法获取实体类，对应的表名 (#18)
必须有该实体类对应的 Mapper 接口

**Comment by downlder** [comment]
我也遇到相同的问题

**Comment by abel533** [comment]
确定扫描到了吗？

**Comment by downlder** [comment]
是spring-boot-devtools惹得祸

**Comment by cymbalhuang** [comment]
@downlder 有解决方案？

**Comment by cymbalhuang** [comment]
解决办法

在resources新建一个文件夹META-INF，新建文件spring-devtools.properties，输入内容restart.include.companycommonlibs=tk/mybatis.*

即可解决

**Comment by abel533** [comment]
@cymbalhuang 最新版本不需要这个配置。。。2.0.3版本。

**Comment by jia-zhen** [comment]
2.0.3版本 还是报了这个错误

**Comment by aluo07** [comment]
我的情况是在dao文件夹下增加了basemapper类，所有mapper都需继承这个基本的basemapper，导致包扫描的时候出现问题，将basemapper文件移除dao文件夹外问题就解决了
