### ISSUE TITLE
大神帮忙看下-----只差把这个示例代码 全部copy过去了。

### ISSUE THREAD

**Issue by helloworldtang** [abel533/MyBatis-Spring-Boot#34]
错误：Caused by: java.lang.InstantiationException: tk.mybatis.mapper.provider.SpecialProvider
	at java.lang.Class.newInstance(Class.java:427)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:85)
	... 136 common frames omitted
Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.SpecialProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)

相关代码已上传到github:https://github.com/helloworldtang/SpringBootCookbook
rest接口：/tx/post
所在class:
com.tangcheng.rest.TxController

**Comment by helloworldtang** [comment]
重新切了个分支：v1.0.0_tx
去年通用mapper，只使用mybatis-spring-boot-starter，就可以正常使用了

**Comment by helloworldtang** [comment]
重新启了一个Module,按照例子中操作了一遍。是ok的
我上面的那个项目中，那个地方的配置干扰了通用Mapper的初始呢？
奇怪

**Comment by abel533** [comment]
上面错误的原因是mapper配置错误，导致通用方法没有被正确的初始化。

**Comment by helloworldtang** [comment]
@abel533 反复把代码与这个例子比对了一下。没有发现错。跟了下代码，发现执行过程中传的参数都对

但还是报错了：

Error invoking SqlProvider method (tk.mybatis.mapper.provider.SpecialProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.SpecialProvider

报错位置：
[
![providermethod-dyn](https://cloud.githubusercontent.com/assets/13701989/24753845/8bbd18e4-1b06-11e7-99d9-06ea98acc15f.png)


有时间给看看呗，没有找到门道啊
示例代码在项目中的位置：
![package-mybati-spring](https://cloud.githubusercontent.com/assets/13701989/24753872/b7d9db92-1b06-11e7-9014-883b3701f14c.png)

**Comment by helloworldtang** [comment]
@abel533 
原来是SpecialProvider.class.newInstance();报错了：

![nosuchmethod-2](https://cloud.githubusercontent.com/assets/13701989/24754294/7a05aa42-1b08-11e7-8629-af7c14da886a.png)
![nosuchmethod-specialprovider](https://cloud.githubusercontent.com/assets/13701989/24754295/7a3ad866-1b08-11e7-87bd-10056bb26d15.png)


为什么呢？

**Comment by helloworldtang** [comment]
今天在对比代码时发现一个：
上面报错项目中MappedStatement.java中sqlSource是tk.mybatis.mapper.provider.SpecialProvider
你给出的例子中却是org.apache.ibatis.scripting.xmltags.DynamicSqlSource

哪个地方的配置决定实例化哪个SqlSource呢？
有错的：
![providersqlsource-mybatis](https://cloud.githubusercontent.com/assets/13701989/24798252/9cbdb7d6-1bc7-11e7-9631-37287052691a.png)

正常的：
![dynamicsqlsource-mybatis](https://cloud.githubusercontent.com/assets/13701989/24798274/a9e2b0f6-1bc7-11e7-8691-a689726ad7e0.png)

**Comment by helloworldtang** [comment]
@abel533 Mapper哪个地方配错了呢。和这个例子中除了class名字外，都是一样的呢？

**Comment by abel533** [comment]
ProviderSqlSource 初始化时不会调用 newInstance 方法。当 Mapper 处理所有的通用方法后，都已经不是 ProviderSqlSource 了，永远都没机会调用 newInstance 了。唯一会导致这个错误的原因就是配置错误导致通用方法没被处理。

你接口都集成的 MyMapper，你按文档配置 mappers 属性试试。

**Comment by helloworldtang** [comment]
@abel533 看看错哪了呢？
又比对了一遍了。都有配置的：
mappers:
![basepackages](https://cloud.githubusercontent.com/assets/13701989/24829541/6232d33c-1ca6-11e7-9907-1d0bd79dd3cf.png)

![basepackages](https://cloud.githubusercontent.com/assets/13701989/24829544/6dc7d9ea-1ca6-11e7-8f91-f0a9b7d6d8c9.png)

![pom-dependency](https://cloud.githubusercontent.com/assets/13701989/24829546/7245d486-1ca6-11e7-90a9-f9c7ab0cf39d.png)

**Comment by helloworldtang** [comment]
发现一个有意思地方：
我这边 通用mapper自动配置没有生产：

上面例子中spring 容器国有这些bean，我写的那个demo就没有

![beans-abel](https://cloud.githubusercontent.com/assets/13701989/24830145/ae542336-1cb2-11e7-937b-1c09560be9c3.png)

**Comment by helloworldtang** [comment]
@abel533 
感觉这是一个bug，看看是那个方面的原因导致的呢?

 问题原因应该是:com.github.pagehelper.autoconfigure.MapperAutoConfiguration和
com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration
没有自动配置。



以MapperAutoConfiguration为例,Spring容器中是有SqlSessionFactory这个实例的，从下面的代码看，MapperAutoConfiguration 是应该会被自动配置，但实际情况是 ----- **没有实例化**：
@Configuration
@ConditionalOnBean({SqlSessionFactory.class})
@EnableConfigurationProperties({MapperProperties.class})
@AutoConfigureAfter({MybatisAutoConfiguration.class})
public class MapperAutoConfiguration {

**Comment by abel533** [comment]
加个 @MapperScan

**Comment by helloworldtang** [comment]
@abel533 
感觉问题出在MapperAutoConfiguration.java的Condition条件上了
看看是不是应该把MapperAutoConfiguration.java上的注解
@ConditionalOnBean({SqlSessionFactory.class})
改成
@ConditionalOnClass({SqlSessionFactory.class})


MapperScan已经加过了。
@MapperScan放在启动的那个class CookbookApplication.java上了

**Comment by helloworldtang** [comment]
@abel533 这个bug不想跟了。回退到使用java config来配置PageInterceptor和通用Mapper.
现在已经Ok。

tips:
经过这个bug搞的，感觉现在离能写mybatis plugin只差一点点了 ☺^_^

**Comment by helloworldtang** [comment]
@abel533 

建议将MapperAutoConfiguration和PageHelperAutoConfiguration的实例化条件改为ConditionalOnClass

应该是spring boot中加载MapperAutoConfiguration和PageHelperAutoConfiguration的时机有差异

spring boot actuator中提供的信息显示，在加载通用Mapper和PageHelper的autoconfig时，SqlSessionFactory.class并没有实例化完成。

![conditiononbeansqlfactory](https://cloud.githubusercontent.com/assets/13701989/25083743/38f4a2ac-238b-11e7-8dad-73fd31ff2dad.png)

**Comment by abel533** [comment]
我这里的启动日志中：
```java
   MapperAutoConfiguration matched:
      - @ConditionalOnBean (types: org.apache.ibatis.session.SqlSessionFactory; SearchStrategy: all) found bean 'sqlSessionFactory' (OnBeanCondition)

   PageHelperAutoConfiguration matched:
      - @ConditionalOnBean (types: org.apache.ibatis.session.SqlSessionFactory; SearchStrategy: all) found bean 'sqlSessionFactory' (OnBeanCondition)
```

**Comment by abel533** [comment]
你使用的 spring boot，以及 pagehelper 和 mapper 的 starter 版本是多少？

**Comment by helloworldtang** [comment]
@abel533 都是从https://github.com/abel533/MyBatis-Spring-Boot.git  copy过去的


        
        <dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper-spring-boot-starter</artifactId>
            <version>1.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.1.0</version>
        </dependency>

**Comment by helloworldtang** [comment]
@abel533  如果单独写一个项目，里面只有https://github.com/abel533/MyBatis-Spring-Boot.git里面的业务逻辑，也是可以的。

但在https://github.com/helloworldtang/spring-boot-cookbook.git这个学习用的小项目中,就会not Matched

**Comment by biezhi** [comment]
@helloworldtang 遇到同样的问题，你解决了吗?

**Comment by helloworldtang** [comment]
现在是能用了，具体什么原因也不清楚。
把相关配置都放在application,properties中就可以。

**Comment by zollty** [comment]
遇到这个问题了，
Caused by: org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.base.BaseSelectProvider.dynamicSQL).  
Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseSelectProvider

我的分析如下：
spring boot项目中用的是mybatis的：
`@MapperScan(basePackages = { "com.xxx.mapper"})`
而传统spring mvc项目中用的是tk.mybatis的：
`<bean class="tk.mybatis.spring.mapper.MapperScannerConfigurer">
      <property name="basePackage" value="com.xxx.mapper" />
</bean>
`

spring-boot那种mapper扫描方式，少了一些 tk.mybatis.spring.mapper.MapperScannerConfigurer 中的操作。所以我猜想可能是这个原因导致。


看了很多spring-boot源码和文档，但是后面总结了一下，其实spring-boot并没有像官方说的那样简便易用，特别是涉及一些复杂配置，spring-boot管理起来很乱。所以，我接下来准备尝试把xml和spring-boot的注释方式结合起来使用，不知道效果会怎样。

**Comment by abel533** [comment]
@zollty 这个错误只有配置错的时候才会出现，就是没有处理通用接口方法导致的。

**Comment by zollty** [comment]
@abel533 据我深入分析，这不是配置错误，而是代码问题。`@MapperScan`注解并不能代替**tk**.mybatis.spring.mapper.MapperScannerConfigurer，如果用`@MapperScan`则少了对GenericBeanDefinition的改造、少了加入`mapperHelper`。

为了验证这个说法，我将`@MapperScan`换成了自己写的`@MyMapperScan`，扫描注解时加上`mapperHelper`并对`BeanDefinitionRegistry registry`进行了处理，自然就解决了这个问题。

建议你提供一个tk.MapperScan，替换Mybatis自带那个。

**Comment by abel533** [comment]
@zollty 你用mapper-starter了吗？这个项目会自动处理通用接口。

**Comment by fengcbo** [comment]
大神们，有什么解决方案吗？我也遇到了类似的错误，所有的配置都对比了一遍，应该没什么错误，但是BaseSelectProvider初始化就是报错。

**Comment by abel533** [comment]
@fengcbo 你用的1.1.1版本的starter？

**Comment by fengcbo** [comment]
恩，用的是1.1.1版本的。只是在@Configuration中引用Mapper会报错，项目启动完成后就可以正常调用了

**Comment by abel533** [comment]
@fengcbo 这种情况会在初始化完成前调用，所以会出错。

**Comment by fengcbo** [comment]
哪有什么方法可以解决这个问题吗？

**Comment by abel533** [comment]
参考:[Spring Boot - 配置排序依赖技巧](http://blog.csdn.net/isea533/article/details/53975720)
让你的配置类在 `MapperAutoConfiguration` 配置类后面执行。

**Comment by fengcbo** [comment]
按照您文章中说的配置了org.springframework.boot.autoconfigure.EnableAutoConfiguration=org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration,\
  com.xxxx.ShiroConfiguration

ShiroConfiguration 没有让spring boot扫描到，但是错误依旧存在。
在网上搜索了好多关于这个错误的问答，感觉都是没有什么结果，希望您能在常见问题中提供一下解决方案，或者能够提供一个相关的项目示例。

**Comment by abel533** [comment]
在 `MapperAutoConfiguration` 和 你的配置类中断点看看那个先执行。

**Comment by fengcbo** [comment]
上面的配置写错了，第一个应该是com.github.pagehelper.autoconfigure.MapperAutoConfiguration。
不过debug看了后，在META-INF/spring.factories 中加入上面的配置后依然是我的ShiroConfiguration先执行。

**Comment by abel533** [comment]
ShiroConfiguration 注解怎么配置的？

**Comment by fengcbo** [comment]
只有一个Configuration注解

**Comment by fengcbo** [comment]
今天大概读了一下spring boot 关于spring.factories解析的过程，spring boot在解析完org.springframework.boot.autoconfigure.EnableAutoConfiguration后的配置后会对结果进行再一次的排序，所以这个配置的顺序不能保证spring boot的解析顺序。您提供的那个方法好像并不可行。

**Comment by ginhom** [comment]
同样的问题，@Configuration类内面用到Mapper,结果出现这个错误了。。。
![image](https://user-images.githubusercontent.com/3000284/29267279-913e5fba-811a-11e7-96f0-58842a4842ad.png)

**Comment by fengcbo** [comment]
Configuration的加载是在Auto Configuration之前的，有几种方式可以让Auto Configuration以前加载，作者的实现没有考虑到Configuration中使用Mapper的情况，要解决目前只能自己重写starter(没找到其他方式)。
<img width="970" alt="2017-08-14 7 50 31" src="https://user-images.githubusercontent.com/9375052/29270766-d9d909a4-812a-11e7-97eb-6b7d52347de0.png">
https://github.com/chanjarster/spring-boot-all-callbacks

**Comment by abel533** [comment]
这里确实有问题。加载太早以至于没有初始化。

**Comment by ZuiSong** [comment]
我也遇到这个问题了，只能Java代码配置，没法用starter

**Comment by fengcbo** [comment]
仿照作者的starter重写了一个，解决了这个问题
https://github.com/fengcbo/mapper-spring-boot

**Comment by ZuiSong** [comment]
应该不需要你重写一个starter吧，可以在你使用mapper的configuration上加上
`@AutoConfigureAfter(MapperAutoConfiguration)`
的注解手动控制顺序就好了啊

**Comment by fengcbo** [comment]
AutoConfigureAfter不能控制Configuration和Auo-Configuration的加载顺序，我测试的是加上AutoConfigureAfter依然不能解决问题，你的应该是没在Configuration使用通用Mapper吧

**Comment by abel533** [comment]
@ZuiSong @fengcbo 看这里：http://blog.csdn.net/isea533/article/details/53975720

**Comment by cgnq** [comment]
最终解决方案是什么呢？

**Comment by abel533** [comment]
@cgnq 使用提供的mapper-starter就行。

**Comment by cgnq** [comment]
嗯，还有一个问题，假如A用到B，不管怎么配置，B一定会先加载。我用shiro的ShiroFilterFactoryBean在配置的时候用通用mapper加入数据库数据，用了spring.factories也没用，最终的解决方案是让ShiroFilterFactoryBean先加载，在写一个
![image](https://user-images.githubusercontent.com/807056/34024705-a132ebb2-e186-11e7-8c18-d1223416e01a.png)

**Comment by 760374564** [comment]
异常信息：
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.base.BaseInsertProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseInsertProvider
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy104.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:57)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy135.insertSelective(Unknown Source)
	at com.jusfoun.common.base.service.impl.BaseDataDtoWithAssociateServiceImpl.saveBase(BaseDataDtoWithAssociateServiceImpl.java:21)
	at com.jusfoun.common.base.service.impl.BaseDataDtoWithAssociateServiceImpl$$FastClassBySpringCGLIB$$bbbe6637.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.jusfoun.web.budget.service.impl.LzPmBudgetServiceImpl$$EnhancerBySpringCGLIB$$b5b7a54d.saveBase(<generated>)
	at com.jusfoun.web.budget.controller.LzPmBudgetController.save(LzPmBudgetController.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at com.jusfoun.web.security.filter.PMSecurityFilter.doFilter(PMSecurityFilter.java:38)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.jusfoun.web.security.filter.JwtAuthenticationTokenFilter.doFilterInternal(JwtAuthenticationTokenFilter.java:118)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.jusfoun.common.config.CORSFilter.doFilter(CORSFilter.java:34)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at com.jusfoun.web.security.filter.PMSecurityFilter.doFilter(PMSecurityFilter.java:38)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.jusfoun.web.security.filter.JwtAuthenticationTokenFilter.doFilterInternal(JwtAuthenticationTokenFilter.java:118)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.base.BaseInsertProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseInsertProvider
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:135)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.getBoundSql(ProviderSqlSource.java:103)
	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:292)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.<init>(BaseStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.<init>(PreparedStatementHandler.java:40)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.<init>(RoutingStatementHandler.java:46)
	at org.apache.ibatis.session.Configuration.newStatementHandler(Configuration.java:558)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy178.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 125 common frames omitted
Caused by: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseInsertProvider
	at java.lang.Class.newInstance(Class.java:427)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:117)
	... 147 common frames omitted
Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseInsertProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 148 common frames omitted
	
解决方能：
	使用MapperScan注解时使用 tk.mybatis.spring.annotation.MapperScan 替换 org.mybatis.spring.annotation.MapperScan，搞定问题，不知道与上面的仁兄是不是同样的问题，这算不算一种解决方案呢？另外如果这里能避免注解的再定义，只使用org.mybatis.spring.annotation.MapperScan 注解就完美了^o^！

**Comment by abel533** [comment]
@760374564 你可以看看文档中配置 Configuration 的用法，用这种方式都不需要 starter，只依赖 mapper 就行了。

**Comment by gatspy** [comment]
@760374564 被这个问题困扰一天了，终于解决了。谢谢！

**Comment by 673793999** [comment]
不用那么麻烦，在启动类上，关注一下@MapperScan，换成tk.mybatis.spring.annotation.MapperScan就解决了

**Comment by zhqiang-li** [comment]
今天使用 starter 2.0.2版本
tk.mybatis.spring.annotation.MapperScan("com.xx.xx.*.mapper")
也报这个错误。

**Comment by ginhom** [comment]
根本原因在于当前引用的类比mapper更早加载了，按着这个思路，我的解决方案是在调用的地方使用Spring上下文类引入mapper，如：
ApplicationContextHolder.context.getBean(Xxxxx.class);

**Comment by abel533** [comment]
@ginhom 最新版本没有这个问题。

@zhqiang-li 如果你用 devtools 了，就试试 2.0.3-beta1 版本。

https://github.com/abel533/Mapper/wiki/faq 有常见原因。

**Comment by jarvisqi** [comment]
@abel533 
用 devtools 了，使用 2.0.3-beta1 版本还是有这个错误，禁用热启动还是会报错。
`import tk.mybatis.spring.annotation.MapperScan; `  
只要就正常使用

**Comment by jacarrichan** [comment]
我也碰到这个问题了，还不能稳定复现。
本机单元测试没有问题，上测试环境偶尔出现问题，很邪门
