### ISSUE TITLE
发现生成的sql与预期的不一样

### ISSUE THREAD

**Issue by helloworldtang** [abel533/MyBatis-Spring-Boot#46]
下面的代码在执行时，发现生成的sql与预期的不一样。预期是
UPDATE car_tt  **set name=?**  WHERE  id = ?
```java

        CarTtDO carTtDO=new CarTtDO();
        carTtDO.setId(1L);
        carTtDO.setName(null);
        carTtDOMapper.updateByPrimaryKey(carTtDO);
```

···java
### Cause: java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :'tt   WHERE  id = ?',expect SET, actual WHERE WHERE : UPDATE car_tt   WHERE  id = ?
; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; sql injection violation, syntax error: syntax error, error in :'tt   WHERE  id = ?',expect SET, actual WHERE WHERE : UPDATE car_tt   WHERE  id = ?; nested exception is java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :'tt   WHERE  id = ?',expect SET, actual WHERE WHERE : UPDATE car_tt   WHERE  id = ?
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy87.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:294)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy88.updateByPrimaryKeySelective(Unknown Source)
	at com.xiaoyi.app.business.car.biz.CarTtBiz.updateTt(CarTtBiz.java:103)
```

**Comment by abel533** [comment]
测试看了，没有发现问题。
测试如下：
```java
CountryMapper mapper = sqlSession.getMapper(CountryMapper.class);
Country country = new Country();
country.setId(174);
country.setCountryname(null);
Assert.assertEquals(1, mapper.updateByPrimaryKey(country));
```
日志如下：
```
DEBUG [main] - ==>  Preparing: UPDATE country SET countryname = ?,countrycode = ? WHERE id = ? 
DEBUG [main] - ==> Parameters: null, null, 174(Integer)
DEBUG [main] - <==    Updates: 1
```

**Comment by helloworldtang** [comment]
是不是有些配置会导致Null会被过虑掉呢？

我这边还是有这个报错
![updatebyprimarykeyselective](https://cloud.githubusercontent.com/assets/13701989/26815884/74460870-4ac1-11e7-82bc-e1adbe8c121c.png)

**Comment by workcheng** [comment]
很多接口就是根据字段是否为null来选择是否去做更新的，你换其他方法试试

**Comment by helloworldtang** [comment]
@workcheng  如果把gpsUrl字段赋值的话，sql就正常了。
这里面用的是通用mapper的方法，没有自己写的

**Comment by abel533** [comment]
`CarTtDO`代码发出来看看。

**Comment by helloworldtang** [comment]
I am so sorry for the late reply!

```java
import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Table(name = "tb_car_tt")
public class CarTtDO implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "insertTime")
    private Date inserttime;

    /**
     * 修改时间
     */
    @Column(name = "modified_time")
    private Date modifiedTime;

    private Integer tid;

    private String uid;

    private String imei;

    private Long time;

    @Column(name = "begin_time")
    private Long beginTime;

    @Column(name = "end_time")
    private Long endTime;

    @Column(name = "begin_longitude")
    private String beginLongitude;

    @Column(name = "begin_latitude")
    private String beginLatitude;

    @Column(name = "end_longitude")
    private String endLongitude;

    @Column(name = "end_latitude")
    private String endLatitude;

    private String name;

    private String hot;

    @Column(name = "idle_time")
    private String idleTime;

    @Column(name = "travel_time")
    private Double travelTime;

    private String distance;

    @Column(name = "idle_consumption")
    private String idleConsumption;

    @Column(name = "travel_consumption")
    private String travelConsumption;

    private String rpm;

    @Column(name = "hst_speed")
    private String hstSpeed;

    private String accelerate;

    private String decelerate;

    @Column(name = "total_distance")
    private String totalDistance;

    @Column(name = "avg_consumption")
    private String avgConsumption;

    @Column(name = "left_oil")
    private String leftOil;

    /**
     * 用于TT_LE计算，无他用
     */
    @Column(name = "avg_speed")
    private String avgSpeed;

    @Column(name = "tt_date")
    private String ttDate;

    /**
     * oss file url
     */
    @Column(name = "source_url")
    private String sourceUrl;

    /**
     * gps file in ali oss url
     */
    @Column(name = "gps_url")
    private String gpsUrl;

    @Column(name = "gps_file_count")
    private Short gpsFileCount;

    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return insertTime
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * @param inserttime
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * 获取修改时间
     *
     * @return modified_time - 修改时间
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * 设置修改时间
     *
     * @param modifiedTime 修改时间
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * @return tid
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * @param tid
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * @return uid
     */
    public String getUid() {
        return uid;
    }

    /**
     * @param uid
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * @return imei
     */
    public String getImei() {
        return imei;
    }

    /**
     * @param imei
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * @return time
     */
    public Long getTime() {
        return time;
    }

    /**
     * @param time
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * @return begin_time
     */
    public Long getBeginTime() {
        return beginTime;
    }

    /**
     * @param beginTime
     */
    public void setBeginTime(Long beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * @return end_time
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * @param endTime
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * @return begin_longitude
     */
    public String getBeginLongitude() {
        return beginLongitude;
    }

    /**
     * @param beginLongitude
     */
    public void setBeginLongitude(String beginLongitude) {
        this.beginLongitude = beginLongitude == null ? null : beginLongitude.trim();
    }

    /**
     * @return begin_latitude
     */
    public String getBeginLatitude() {
        return beginLatitude;
    }

    /**
     * @param beginLatitude
     */
    public void setBeginLatitude(String beginLatitude) {
        this.beginLatitude = beginLatitude == null ? null : beginLatitude.trim();
    }

    /**
     * @return end_longitude
     */
    public String getEndLongitude() {
        return endLongitude;
    }

    /**
     * @param endLongitude
     */
    public void setEndLongitude(String endLongitude) {
        this.endLongitude = endLongitude == null ? null : endLongitude.trim();
    }

    /**
     * @return end_latitude
     */
    public String getEndLatitude() {
        return endLatitude;
    }

    /**
     * @param endLatitude
     */
    public void setEndLatitude(String endLatitude) {
        this.endLatitude = endLatitude == null ? null : endLatitude.trim();
    }

    /**
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * @return hot
     */
    public String getHot() {
        return hot;
    }

    /**
     * @param hot
     */
    public void setHot(String hot) {
        this.hot = hot == null ? null : hot.trim();
    }

    /**
     * @return idle_time
     */
    public String getIdleTime() {
        return idleTime;
    }

    /**
     * @param idleTime
     */
    public void setIdleTime(String idleTime) {
        this.idleTime = idleTime == null ? null : idleTime.trim();
    }

    /**
     * @return travel_time
     */
    public Double getTravelTime() {
        return travelTime;
    }

    /**
     * @param travelTime
     */
    public void setTravelTime(Double travelTime) {
        this.travelTime = travelTime;
    }

    /**
     * @return distance
     */
    public String getDistance() {
        return distance;
    }

    /**
     * @param distance
     */
    public void setDistance(String distance) {
        this.distance = distance == null ? null : distance.trim();
    }

    /**
     * @return idle_consumption
     */
    public String getIdleConsumption() {
        return idleConsumption;
    }

    /**
     * @param idleConsumption
     */
    public void setIdleConsumption(String idleConsumption) {
        this.idleConsumption = idleConsumption == null ? null : idleConsumption.trim();
    }

    /**
     * @return travel_consumption
     */
    public String getTravelConsumption() {
        return travelConsumption;
    }

    /**
     * @param travelConsumption
     */
    public void setTravelConsumption(String travelConsumption) {
        this.travelConsumption = travelConsumption == null ? null : travelConsumption.trim();
    }

    /**
     * @return rpm
     */
    public String getRpm() {
        return rpm;
    }

    /**
     * @param rpm
     */
    public void setRpm(String rpm) {
        this.rpm = rpm == null ? null : rpm.trim();
    }

    /**
     * @return hst_speed
     */
    public String getHstSpeed() {
        return hstSpeed;
    }

    /**
     * @param hstSpeed
     */
    public void setHstSpeed(String hstSpeed) {
        this.hstSpeed = hstSpeed == null ? null : hstSpeed.trim();
    }

    /**
     * @return accelerate
     */
    public String getAccelerate() {
        return accelerate;
    }

    /**
     * @param accelerate
     */
    public void setAccelerate(String accelerate) {
        this.accelerate = accelerate == null ? null : accelerate.trim();
    }

    /**
     * @return decelerate
     */
    public String getDecelerate() {
        return decelerate;
    }

    /**
     * @param decelerate
     */
    public void setDecelerate(String decelerate) {
        this.decelerate = decelerate == null ? null : decelerate.trim();
    }

    /**
     * @return total_distance
     */
    public String getTotalDistance() {
        return totalDistance;
    }

    /**
     * @param totalDistance
     */
    public void setTotalDistance(String totalDistance) {
        this.totalDistance = totalDistance == null ? null : totalDistance.trim();
    }

    /**
     * @return avg_consumption
     */
    public String getAvgConsumption() {
        return avgConsumption;
    }

    /**
     * @param avgConsumption
     */
    public void setAvgConsumption(String avgConsumption) {
        this.avgConsumption = avgConsumption == null ? null : avgConsumption.trim();
    }

    /**
     * @return left_oil
     */
    public String getLeftOil() {
        return leftOil;
    }

    /**
     * @param leftOil
     */
    public void setLeftOil(String leftOil) {
        this.leftOil = leftOil == null ? null : leftOil.trim();
    }

    /**
     * 获取用于TT_LE计算，无他用
     *
     * @return avg_speed - 用于TT_LE计算，无他用
     */
    public String getAvgSpeed() {
        return avgSpeed;
    }

    /**
     * 设置用于TT_LE计算，无他用
     *
     * @param avgSpeed 用于TT_LE计算，无他用
     */
    public void setAvgSpeed(String avgSpeed) {
        this.avgSpeed = avgSpeed == null ? null : avgSpeed.trim();
    }

    /**
     * @return tt_date
     */
    public String getTtDate() {
        return ttDate;
    }

    /**
     * @param ttDate
     */
    public void setTtDate(String ttDate) {
        this.ttDate = ttDate == null ? null : ttDate.trim();
    }

    /**
     * 获取oss file url
     *
     * @return source_url - oss file url
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * 设置oss file url
     *
     * @param sourceUrl oss file url
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * 获取gps file in ali oss url
     *
     * @return gps_url - gps file in ali oss url
     */
    public String getGpsUrl() {
        return gpsUrl;
    }

    /**
     * 设置gps file in ali oss url
     *
     * @param gpsUrl gps file in ali oss url
     */
    public void setGpsUrl(String gpsUrl) {
        this.gpsUrl = gpsUrl == null ? null : gpsUrl.trim();
    }

    /**
     * @return gps_file_count
     */
    public Short getGpsFileCount() {
        return gpsFileCount;
    }

    /**
     * @param gpsFileCount
     */
    public void setGpsFileCount(Short gpsFileCount) {
        this.gpsFileCount = gpsFileCount;
    }
}
```
